services:
  api-service:
    image: node:18.19.0
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    depends_on:
      - db
    links:
      - 'db'
    ports:
      - 3002:3002
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
